#!/bin/bash
#
# Author: Chris Aumann <me@chr4.org>
# Set /etc/resolv.conf from OpenNebula context (if given) unless it was already configured.

# Check whether dns is already configured
[ -s /etc/resolv.conf ] && exit 0

nameservers=$(
    DNS_VARIABLES="DNS $(env |sed 's/=.*$//' |grep -E '^ETH[0-9]+_DNS$' |sort)"

    for var in ${DNS_VARIABLES}; do
        value=$(eval "echo \"\${$var}\"")
        if [ -n "$value" ]; then
            echo "$value"
        fi
    done
)

searchdomains=$(
    SEARCH_VARIABLES="SEARCH_DOMAIN $(env |sed 's/=.*$//' |grep -E '^ETH[0-9]+_SEARCH_DOMAIN$' |sort)"

    for var in ${SEARCH_VARIABLES}; do
        value=$(eval "echo \"\${$var}\"")
        if [ -n "$value" ]; then
            echo "$value"
        fi
    done
)

[ -z "$nameservers" ] && exit 0

echo -n '' > /etc/resolv.conf

for nameserver in $nameservers; do
    echo nameserver $nameserver >> /etc/resolv.conf
done

[ -z "$searchdomains" ] && exit 0

echo search $searchdomains >> /etc/resolv.conf
