#!/bin/bash
#
# Author: Chris Aumann <me@chr4.org>
# Set /etc/hostname from OpenNebula context (if given) unless hostname was already set.

if [ -n "$SET_HOSTNAME" ]; then
    # Check whether hostname is already set
    if [ ! -s /etc/hostname ]; then
        echo $SET_HOSTNAME > /etc/hostname
        hostname $SET_HOSTNAME
    fi

    # Check whether /etc/hosts is already present
    if [ ! -s /etc/hosts ]; then
      # If a domain is given, add fqdn to /etc/hosts, otherwise only the hostname
      if [ -n "$SEARCH_DOMAIN" ]; then
          HOSTS_ENTRY="$SET_HOSTNAME ${SET_HOSTNAME}.${SEARCH_DOMAIN}"
      else
          HOSTS_ENTRY="$SET_HOSTNAME"
      fi

      # Deploy /etc/hosts with correct hostname association
      cat > /etc/hosts <<-EOS
127.0.0.1       localhost
127.0.1.1       $HOSTS_ENTRY

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOS

  fi
fi
